version: "3.0"
services:
  database:
    container_name: db_postgres
    image: postgres:13
    env_file: .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./backups:/backups
