version: "3.8"
services:
  database:
    container_name: db_postgres
    image: postgres:13
    env_file: env
    restart: always
    # Descomentar para debugear
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/log:/var/log/postgresql