version: "3.0"
services:
  database:
    container_name: ${CONTAINER_NAME}
    image: postgres:13
    env_file: .env
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./backups:/backups
